// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;


      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD86Zu3Y9SrqC5bGFHurKclWjrOKm_BZzU',
    appId: '1:317184213705:android:aa3e7c0051c83961cdc318',
    messagingSenderId: '317184213705',
    projectId: 'instagram-12824',
    storageBucket: 'instagram-12824.firebasestorage.app',
  );


  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdStbbseBVvgZ4ufQD45jH1Ow0Q4YzrcQ',
    appId: '1:317184213705:web:68b16ca6e3e8bafbcdc318',
    messagingSenderId: '317184213705',
    projectId: 'instagram-12824',
    authDomain: 'instagram-12824.firebaseapp.com',
    storageBucket: 'instagram-12824.firebasestorage.app',
    measurementId: 'G-7YTC82M8M6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJGhfAJEOFZw6D305cYxv8JL7spen-wSk',
    appId: '1:317184213705:ios:01c7a7ede4697c54cdc318',
    messagingSenderId: '317184213705',
    projectId: 'instagram-12824',
    storageBucket: 'instagram-12824.firebasestorage.app',
    iosBundleId: 'com.example.instagram',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdStbbseBVvgZ4ufQD45jH1Ow0Q4YzrcQ',
    appId: '1:317184213705:web:782bfeeee4d95b68cdc318',
    messagingSenderId: '317184213705',
    projectId: 'instagram-12824',
    authDomain: 'instagram-12824.firebaseapp.com',
    storageBucket: 'instagram-12824.firebasestorage.app',
    measurementId: 'G-MZ5GWZ356B',
  );
}
